### ISSUE TITLE
Wrong VertexLayoutBuilder semantics

### ISSUE THREAD

**Issue by BenjaminSchaaf** [emoon/bgfx-rs#10]
I encountered some crashes/invalid rendering when using multiple `VertexLayoutBuilder`. I narrowed this down to `VertexLayoutBuilder.end()` not being called by me, but in doing so I found numerous issues with `VertexLayoutBuilder`:

* `begin`, `add` and `end` mutate the builder but don't take a mutable reference
* `VertexLayoutBuilder` is able to be passed to various APIs without `end` being called. A new type safely encapsulating this requirement would be preferred.
* `begin` and `add` both return `&Self`, meaning you can't assign their result to a variable. AFAIK `Self` is idiomatic.

I'm working on a PR for this.

**Comment by emoon** [comment]
Thanks for the report. The way `bgfx-rs` is done is that the majority of code is auto-generated from this file https://github.com/bkaradzic/bgfx/blob/master/scripts/bgfx.idl using this (right now quite messy/hardcoded) code https://github.com/emoon/bgfx-rs-bindgen/blob/main/src/main.rs 

While I will accept a PR for this, I will likely need to re-implement it later on in the generator.

**Comment by BenjaminSchaaf** [comment]
Unfortunately even if I fix the bindgen repo to not use hard-coded paths it's still panicking, and I don't really want to look further into that. I'll fix it in here for now.

**Comment by emoon** [comment]
> Unfortunately even if I fix the bindgen repo to not use hard-coded paths it's still panicking, and I don't really want to look further into that. I'll fix it in here for now.

Yes that is fine. I'm planning to remove the hard coding + some cleanup to the code, but I just haven't gotten around to do it

**Comment by emoon** [comment]
@BenjaminSchaaf hey, just FYI 0.15 has been released which includes your changes (and also BGFX updated to latest version)

**Comment by BenjaminSchaaf** [comment]
@emoon Awesome, thanks :)
