### ISSUE TITLE
Platform specific examples.

### ISSUE THREAD

**Issue by atonamy** [emoon/bgfx-rs#12]
Could be nice to provide examples for iOS/Android boilerplate code to get started.

**Comment by emoon** [comment]
I don't program myself for those platforms so I can't do it, but if someone would be willing to implement it that would be great.

**Comment by const-volatile** [comment]
Just saw this issue now - I've created an boilerplate example running on android [here](https://github.com/const-volatile/android-bgfx-rs-example). There were some issues in the winit crate at the time, so this relies on an unofficial fork of winit (probably outdated by now).
