### ISSUE TITLE
Linking with 'link.exe' failed: exit code: 1120 (Windows, both MSVC and GNU)

### ISSUE THREAD

**Issue by dillionnason** [emoon/bgfx-rs#13]
I am getting this error compiling on Windows in debug: 

```libbgfx_sys-3a085ea111dd24ba.rlib(image.o) : error LNK2019: unresolved external symbol "bool __cdecl astc_codec::ASTCDecompressToRGBA(unsigned char const *,unsigned __int64,unsigned __int64,unsigned __int64,enum astc_codec::FootprintType,unsigned char *,unsigned __int64,unsigned __int64)" (?ASTCDecompressToRGBA@astc_codec@@YA_NPEBE_K11W4FootprintType@1@PEAE11@Z) referenced in function "void __cdecl bimg::imageDecodeToRgba8(struct bx::AllocatorI *,void *,void const *,unsigned int,unsigned int,unsigned int,enum bimg::TextureFormat::Enum)" (?imageDecodeToRgba8@bimg@@YAXPEAUAllocatorI@bx@@PEAXPEBXIIIW4Enum@TextureFormat@1@@Z)```

I am able to compile and run in with `--release`. I am using CLion, but the error also occurs when I try and build directly with Cargo. Steps I've taken to try and fix it:

- Switching to the GNU toolchain, but it looks like the issue is in linking bimg and not in the Rust part of the program. 
- Updating my VC 2019 toolchain (MSVC 14.29.30133). 
- Updating to the VC 2022 toolchain (MSVC 14.24.31933).

**Comment by emoon** [comment]
Thanks for the report! I will fix it later today

**Comment by emoon** [comment]
Sorry I didn't get around to fixing it yesterday, I will try to do it today instead.

**Comment by emoon** [comment]
Fixed in `0.16`
