### ISSUE TITLE
hello , i would like to be maintainer of this crate

### ISSUE THREAD

**Issue by Abhinavpatel00** [emoon/bgfx-rs#15]
excited to discuss about what's next

**Comment by emoon** [comment]
Hey!

That is great! The next step would be for me to transfer the whole repository over to you. This is something I haven't done before, but reading here it seems to be possible https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

Should I start doing that?

**Comment by Abhinavpatel00** [comment]
yes you can start doing  :)

**Comment by emoon** [comment]
You should have a request about transfer now

**Comment by Abhinavpatel00** [comment]
> You should have a request about transfer now

thank you :)

**Comment by emoon** [comment]
sys repo coming your way also now

**Comment by emoon** [comment]
@Abhinavpatel00 I have sent a request for bgfx-sys now also to be transfered

**Comment by Abhinavpatel00** [comment]
great responsibilities i will try best to learn and improve those ,would you mind if i want you guidance on something ?

**Comment by emoon** [comment]
Both the bgfx-sys and bgfx-rs belongs together, but if you want you could fold them into one. I thought it was better to keep them separate as it makes testing easier when integrating an updated version of bgfx in sys first and then check if the high level API works.

**Comment by emoon** [comment]
If you have any questions just let me know.
