### ISSUE TITLE
Unable to compile. MSVC error 1120

### ISSUE THREAD

**Issue by Syntaxxor** [emoon/bgfx-rs#3]
I'm using the most recent stable build of Rust, with the MSVC compiler. When I try to compile my own project or one of the examples, it fails with error code 1120, and complains about several unresolved external symbols. Is there a special setup step I haven't noticed? This error occurs with all 3 examples, though 2 of them have a typo in the code that has to be fixed first.

**Comment by emoon** [comment]
Thanks for the report! I will take a look

**Comment by emoon** [comment]
Oh I see that I only auto build for Linux currently :man_facepalming: I will have a look at it

**Comment by emoon** [comment]
I made a quick fix for it. Right now only `--release` works because of one remaining issue, otherwise it should run fine now.

**Comment by Jimmyberf103** [comment]
Sadly it's still not compiling without a release flag. I wrapped bgfx into a workspace with these toml configurations

opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = "unwind"
incremental = false
overflow-checks = false

and it works without --release flag now. But now by default

**Comment by emoon** [comment]
I can look at fixing it today

**Comment by emoon** [comment]
Should be fixed in bgfx-rs 0.8 (sorry for the delay, I forgot about this issue :( )
