### ISSUE TITLE
Caps::limits should be CapsLimits, but is currently Limits

### ISSUE THREAD

**Issue by nice-sprite** [emoon/bgfx-rs#7]
bgfx documentation for the [Limits](https://bkaradzic.github.io/bgfx/bgfx.html?highlight=limits#_CPPv4N4bgfx4Caps6LimitsE) structure does not match the definition in https://github.com/emoon/bgfx-rs/blob/49f8ea182bfec453393c8fa0658c49a158ecb297/src/static_lib.rs#L1640-L1649
Which is referenced in this struct returned from `bgfx::get_caps()`
https://github.com/emoon/bgfx-rs/blob/49f8ea182bfec453393c8fa0658c49a158ecb297/src/static_lib.rs#L1552-L1596

I think `Caps::limits` should be changed from `Limits` to `CapsLimits`, as the CapsLimits struct reflects what the documentation says `bgfx::get_caps()` should return.

**Comment by emoon** [comment]
Thanks for the report. This has now bee fixed in `0.11`
