### ISSUE TITLE
Missing macros

### ISSUE THREAD

**Issue by NoFr1ends** [emoon/bgfx-rs#8]
It seems like macros like ``BGFX_STATE_BLEND_FUNC`` are missing in both ``bgfx_sys`` and ``bgfx_rs`` while being mentioned in the documentation at StateBlendFlags e.g. 

```
bgfx-rs = "0.13"
bgfx-sys = "0.9.0"
```

**Comment by emoon** [comment]
Thanks for pointing this out. I will take a look at it tomorrow.

**Comment by emoon** [comment]
Added (inline) functions over here https://github.com/emoon/bgfx-rs/blob/main/src/static_lib.rs#L5856 for blending (and also added the helper macros for various blend types)
